package atlas.mdt.dcs.data;

// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * AlCycerr generated by hbm2java
 */
@Entity
@Table(name = "AL_CYCERR", schema = "ATLAS_MDT_DCS")
@NamedQueries({
		@NamedQuery(name = AlCycerr.QUERY_GET_HISTORY, query = " FROM AlCycerr as cycerr"
				+ " WHERE cycerr.id.startTime >= :since AND cycerr.id.startTime < :until"),
		@NamedQuery(name = AlCycerr.QUERY_FIND_CYCLEBYID, query = " FROM AlCycerr as cycerr"
				+ " WHERE cycerr.id.cycleNumber = :id") })
public class AlCycerr implements java.io.Serializable {

	public static final String QUERY_GET_HISTORY = "alcycerr.gethistory";
	public static final String QUERY_FIND_CYCLEBYID = "alcycerr.findcyclebyid";

	private AlCycleId id;
	private Long tend;
	private Long bimages;
	private Long berr;
	private Long rimages;
	private Long rerr;
	private Long timages;
	private Long terr;
	private Long ec;

	public AlCycerr() {
	}

	public AlCycerr(AlCycleId id) {
		this.id = id;
	}

	public AlCycerr(AlCycleId id, Long tend, Long bimages, Long berr,
			Long rimages, Long rerr, Long timages, Long terr, Long ec) {
		this.id = id;
		this.tend = tend;
		this.bimages = bimages;
		this.berr = berr;
		this.rimages = rimages;
		this.rerr = rerr;
		this.timages = timages;
		this.terr = terr;
		this.ec = ec;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cycleNumber", column = @Column(name = "CYCLE_NUMBER", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "startTime", column = @Column(name = "TSTART", nullable = false, precision = 22, scale = 0)) })
	public AlCycleId getId() {
		return this.id;
	}

	public void setId(AlCycleId id) {
		this.id = id;
	}

	@Column(name = "TEND", precision = 12, scale = 0)
	public Long getTend() {
		return this.tend;
	}

	public void setTend(Long tend) {
		this.tend = tend;
	}

	@Column(name = "BIMAGES", precision = 10, scale = 0)
	public Long getBimages() {
		return this.bimages;
	}

	public void setBimages(Long bimages) {
		this.bimages = bimages;
	}

	@Column(name = "BERR", precision = 10, scale = 0)
	public Long getBerr() {
		return this.berr;
	}

	public void setBerr(Long berr) {
		this.berr = berr;
	}

	@Column(name = "RIMAGES", precision = 10, scale = 0)
	public Long getRimages() {
		return this.rimages;
	}

	public void setRimages(Long rimages) {
		this.rimages = rimages;
	}

	@Column(name = "RERR", precision = 10, scale = 0)
	public Long getRerr() {
		return this.rerr;
	}

	public void setRerr(Long rerr) {
		this.rerr = rerr;
	}

	@Column(name = "TIMAGES", precision = 10, scale = 0)
	public Long getTimages() {
		return this.timages;
	}

	public void setTimages(Long timages) {
		this.timages = timages;
	}

	@Column(name = "TERR", precision = 10, scale = 0)
	public Long getTerr() {
		return this.terr;
	}

	public void setTerr(Long terr) {
		this.terr = terr;
	}

	@Column(name = "EC", precision = 10, scale = 0)
	public Long getEc() {
		return this.ec;
	}

	public void setEc(Long ec) {
		this.ec = ec;
	}

}
