package atlas.mdt.dcs.data;
// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AlCycle generated by hbm2java
 */
@Entity
@Table(name="AL_CYCLE"
    ,schema="ATLAS_MDT_DCS"
)
public class AlCycle  implements java.io.Serializable {


     private AlCycleId id;
     private BigDecimal endTime;

    public AlCycle() {
    }

	
    public AlCycle(AlCycleId id) {
        this.id = id;
    }
    public AlCycle(AlCycleId id, BigDecimal endTime) {
       this.id = id;
       this.endTime = endTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cycleNumber", column=@Column(name="CYCLE_NUMBER", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="startTime", column=@Column(name="START_TIME", nullable=false, precision=22, scale=0) ) } )
    public AlCycleId getId() {
        return this.id;
    }
    
    public void setId(AlCycleId id) {
        this.id = id;
    }

    
    @Column(name="END_TIME", precision=22, scale=0)
    public BigDecimal getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(BigDecimal endTime) {
        this.endTime = endTime;
    }




}


