package atlas.mdt.dcs.data;

// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlCycleId generated by hbm2java
 */
@Embeddable
public class AlCycleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8195144794751519933L;
	private BigDecimal cycleNumber;
	private BigDecimal startTime;

	public AlCycleId() {
	}

	public AlCycleId(BigDecimal cycleNumber, BigDecimal startTime) {
		this.cycleNumber = cycleNumber;
		this.startTime = startTime;
	}

	@Column(name = "CYCLE_NUMBER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCycleNumber() {
		return this.cycleNumber;
	}

	public void setCycleNumber(BigDecimal cycleNumber) {
		this.cycleNumber = cycleNumber;
	}

	@Column(name = "START_TIME", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStartTime() {
		return this.startTime;
	}

	public void setStartTime(BigDecimal startTime) {
		this.startTime = startTime;
	}

}
