package atlas.mdt.dcs.data;
// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlDBnds generated by hbm2java
 */
@Entity
@Table(name="AL_D_BNDS"
    ,schema="ATLAS_MDT_DCS"
)
public class AlDBnds  implements java.io.Serializable {


     private long imageId;
     private BigDecimal stime;
     private BigDecimal pos5vNom;
     private BigDecimal pos5vBnd;
     private BigDecimal pos5cNom;
     private BigDecimal pos5cBnd;
     private BigDecimal pos15vNom;
     private BigDecimal pos15vBnd;
     private BigDecimal pos15cNom;
     private BigDecimal pos15cBnd;
     private BigDecimal neg15vNom;
     private BigDecimal neg15vBnd;
     private BigDecimal neg15cNom;
     private BigDecimal neg15cBnd;

    public AlDBnds() {
    }

	
    public AlDBnds(long imageId, BigDecimal stime) {
        this.imageId = imageId;
        this.stime = stime;
    }
    public AlDBnds(long imageId, BigDecimal stime, BigDecimal pos5vNom, BigDecimal pos5vBnd, BigDecimal pos5cNom, BigDecimal pos5cBnd, BigDecimal pos15vNom, BigDecimal pos15vBnd, BigDecimal pos15cNom, BigDecimal pos15cBnd, BigDecimal neg15vNom, BigDecimal neg15vBnd, BigDecimal neg15cNom, BigDecimal neg15cBnd) {
       this.imageId = imageId;
       this.stime = stime;
       this.pos5vNom = pos5vNom;
       this.pos5vBnd = pos5vBnd;
       this.pos5cNom = pos5cNom;
       this.pos5cBnd = pos5cBnd;
       this.pos15vNom = pos15vNom;
       this.pos15vBnd = pos15vBnd;
       this.pos15cNom = pos15cNom;
       this.pos15cBnd = pos15cBnd;
       this.neg15vNom = neg15vNom;
       this.neg15vBnd = neg15vBnd;
       this.neg15cNom = neg15cNom;
       this.neg15cBnd = neg15cBnd;
    }
   
     @Id 

    
    @Column(name="IMAGE_ID", nullable=false, precision=10, scale=0)
    public long getImageId() {
        return this.imageId;
    }
    
    public void setImageId(long imageId) {
        this.imageId = imageId;
    }

    
    @Column(name="STIME", nullable=false, precision=38, scale=0)
    public BigDecimal getStime() {
        return this.stime;
    }
    
    public void setStime(BigDecimal stime) {
        this.stime = stime;
    }

    
    @Column(name="POS5V_NOM", precision=22, scale=0)
    public BigDecimal getPos5vNom() {
        return this.pos5vNom;
    }
    
    public void setPos5vNom(BigDecimal pos5vNom) {
        this.pos5vNom = pos5vNom;
    }

    
    @Column(name="POS5V_BND", precision=22, scale=0)
    public BigDecimal getPos5vBnd() {
        return this.pos5vBnd;
    }
    
    public void setPos5vBnd(BigDecimal pos5vBnd) {
        this.pos5vBnd = pos5vBnd;
    }

    
    @Column(name="POS5C_NOM", precision=22, scale=0)
    public BigDecimal getPos5cNom() {
        return this.pos5cNom;
    }
    
    public void setPos5cNom(BigDecimal pos5cNom) {
        this.pos5cNom = pos5cNom;
    }

    
    @Column(name="POS5C_BND", precision=22, scale=0)
    public BigDecimal getPos5cBnd() {
        return this.pos5cBnd;
    }
    
    public void setPos5cBnd(BigDecimal pos5cBnd) {
        this.pos5cBnd = pos5cBnd;
    }

    
    @Column(name="POS15V_NOM", precision=22, scale=0)
    public BigDecimal getPos15vNom() {
        return this.pos15vNom;
    }
    
    public void setPos15vNom(BigDecimal pos15vNom) {
        this.pos15vNom = pos15vNom;
    }

    
    @Column(name="POS15V_BND", precision=22, scale=0)
    public BigDecimal getPos15vBnd() {
        return this.pos15vBnd;
    }
    
    public void setPos15vBnd(BigDecimal pos15vBnd) {
        this.pos15vBnd = pos15vBnd;
    }

    
    @Column(name="POS15C_NOM", precision=22, scale=0)
    public BigDecimal getPos15cNom() {
        return this.pos15cNom;
    }
    
    public void setPos15cNom(BigDecimal pos15cNom) {
        this.pos15cNom = pos15cNom;
    }

    
    @Column(name="POS15C_BND", precision=22, scale=0)
    public BigDecimal getPos15cBnd() {
        return this.pos15cBnd;
    }
    
    public void setPos15cBnd(BigDecimal pos15cBnd) {
        this.pos15cBnd = pos15cBnd;
    }

    
    @Column(name="NEG15V_NOM", precision=22, scale=0)
    public BigDecimal getNeg15vNom() {
        return this.neg15vNom;
    }
    
    public void setNeg15vNom(BigDecimal neg15vNom) {
        this.neg15vNom = neg15vNom;
    }

    
    @Column(name="NEG15V_BND", precision=22, scale=0)
    public BigDecimal getNeg15vBnd() {
        return this.neg15vBnd;
    }
    
    public void setNeg15vBnd(BigDecimal neg15vBnd) {
        this.neg15vBnd = neg15vBnd;
    }

    
    @Column(name="NEG15C_NOM", precision=22, scale=0)
    public BigDecimal getNeg15cNom() {
        return this.neg15cNom;
    }
    
    public void setNeg15cNom(BigDecimal neg15cNom) {
        this.neg15cNom = neg15cNom;
    }

    
    @Column(name="NEG15C_BND", precision=22, scale=0)
    public BigDecimal getNeg15cBnd() {
        return this.neg15cBnd;
    }
    
    public void setNeg15cBnd(BigDecimal neg15cBnd) {
        this.neg15cBnd = neg15cBnd;
    }




}


