package atlas.mdt.dcs.data;

// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AlFailed generated by hbm2java
 */
@Entity
@Table(name = "AL_FAILED", schema = "ATLAS_MDT_DCS")
public class AlFailed implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8339967466682665948L;
	private AlFailedId id;
	private BigDecimal cycleSince;
	private BigDecimal cycleUntil;
	private BigDecimal failed;
	private String userComment;

	public AlFailed() {
	}

	public AlFailed(AlFailedId id, BigDecimal cycleSince) {
		this.id = id;
		this.cycleSince = cycleSince;
	}

	public AlFailed(AlFailedId id, BigDecimal cycleSince,
			BigDecimal cycleUntil, BigDecimal failed, String userComment) {
		this.id = id;
		this.cycleSince = cycleSince;
		this.cycleUntil = cycleUntil;
		this.failed = failed;
		this.userComment = userComment;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "stime", column = @Column(name = "STIME", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "imageId", column = @Column(name = "IMAGE_ID", nullable = false, precision = 10, scale = 0)) })
	public AlFailedId getId() {
		return this.id;
	}

	public void setId(AlFailedId id) {
		this.id = id;
	}

	@Column(name = "CYCLE_SINCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCycleSince() {
		return this.cycleSince;
	}

	public void setCycleSince(BigDecimal cycleSince) {
		this.cycleSince = cycleSince;
	}

	@Column(name = "CYCLE_UNTIL", precision = 22, scale = 0)
	public BigDecimal getCycleUntil() {
		return this.cycleUntil;
	}

	public void setCycleUntil(BigDecimal cycleUntil) {
		this.cycleUntil = cycleUntil;
	}

	@Column(name = "FAILED", precision = 22, scale = 0)
	public BigDecimal getFailed() {
		return this.failed;
	}

	public void setFailed(BigDecimal failed) {
		this.failed = failed;
	}

	@Column(name = "USER_COMMENT", length = 150)
	public String getUserComment() {
		return this.userComment;
	}

	public void setUserComment(String userComment) {
		this.userComment = userComment;
	}

}
