package atlas.mdt.dcs.data;
// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlHwfailId generated by hbm2java
 */
@Embeddable
public class AlHwfailId  implements java.io.Serializable {


     private BigDecimal cycleNumber;
     private BigDecimal endTime;
     private String crate;
     private Integer driver;
     private Integer mux;

    public AlHwfailId() {
    }

    public AlHwfailId(BigDecimal cycleNumber, BigDecimal endTime, String crate, Integer driver, Integer mux) {
       this.cycleNumber = cycleNumber;
       this.endTime = endTime;
       this.crate = crate;
       this.driver = driver;
       this.mux = mux;
    }
   


    @Column(name="CYCLE_NUMBER", nullable=false, precision=22, scale=0)
    public BigDecimal getCycleNumber() {
        return this.cycleNumber;
    }
    
    public void setCycleNumber(BigDecimal cycleNumber) {
        this.cycleNumber = cycleNumber;
    }


    @Column(name="END_TIME", nullable=false, precision=20, scale=0)
    public BigDecimal getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(BigDecimal endTime) {
        this.endTime = endTime;
    }


    @Column(name="CRATE", nullable=false, length=8)
    public String getCrate() {
        return this.crate;
    }
    
    public void setCrate(String crate) {
        this.crate = crate;
    }


    @Column(name="DRIVER", nullable=false, precision=8, scale=0)
    public Integer getDriver() {
        return this.driver;
    }
    
    public void setDriver(Integer driver) {
        this.driver = driver;
    }


    @Column(name="MUX", nullable=false, precision=8, scale=0)
    public Integer getMux() {
        return this.mux;
    }
    
    public void setMux(Integer mux) {
        this.mux = mux;
    }




}


