package atlas.mdt.dcs.data;
// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlTBnds generated by hbm2java
 */
@Entity
@Table(name="AL_T_BNDS"
    ,schema="ATLAS_MDT_DCS"
)
public class AlTBnds  implements java.io.Serializable {


     private long imageId;
     private BigDecimal stime;
     private BigDecimal tempNom;
     private BigDecimal tempBnd;

    public AlTBnds() {
    }

	
    public AlTBnds(long imageId, BigDecimal stime) {
        this.imageId = imageId;
        this.stime = stime;
    }
    public AlTBnds(long imageId, BigDecimal stime, BigDecimal tempNom, BigDecimal tempBnd) {
       this.imageId = imageId;
       this.stime = stime;
       this.tempNom = tempNom;
       this.tempBnd = tempBnd;
    }
   
     @Id 

    
    @Column(name="IMAGE_ID", nullable=false, precision=10, scale=0)
    public long getImageId() {
        return this.imageId;
    }
    
    public void setImageId(long imageId) {
        this.imageId = imageId;
    }

    
    @Column(name="STIME", nullable=false, precision=38, scale=0)
    public BigDecimal getStime() {
        return this.stime;
    }
    
    public void setStime(BigDecimal stime) {
        this.stime = stime;
    }

    
    @Column(name="TEMP_NOM", precision=22, scale=0)
    public BigDecimal getTempNom() {
        return this.tempNom;
    }
    
    public void setTempNom(BigDecimal tempNom) {
        this.tempNom = tempNom;
    }

    
    @Column(name="TEMP_BND", precision=22, scale=0)
    public BigDecimal getTempBnd() {
        return this.tempBnd;
    }
    
    public void setTempBnd(BigDecimal tempBnd) {
        this.tempBnd = tempBnd;
    }




}


