package atlas.mdt.dcs.data;
// Generated Aug 31, 2012 4:54:30 PM by Hibernate Tools 3.4.0.CR1


import io.utils.MyPrinterHandler;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TImages generated by hbm2java
 */
@Entity
@Table(name="T_IMAGES"
    ,schema="ATLAS_MDT_DCS"
)
public class TImages  implements java.io.Serializable, EcConfImage {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5450050589580213175L;

	private Long imageId;
     private String imageName;
     private String cameraCrate;
     private Long cameraDriver;
     private Long cameraMux;

    public TImages() {
    }

	
    public TImages(Long imageId, String imageName) {
        this.imageId = imageId;
        this.imageName = imageName;
    }
    public TImages(Long imageId, String imageName, String cameraCrate, Long cameraDriver, Long cameraMux) {
       this.imageId = imageId;
       this.imageName = imageName;
       this.cameraCrate = cameraCrate;
       this.cameraDriver = cameraDriver;
       this.cameraMux = cameraMux;
    }
   
     @Id 

    
    @Column(name="IMAGE_ID", nullable=false, precision=10, scale=0)
    public Long getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    
    @Column(name="IMAGE_NAME", unique=true, nullable=false, length=64)
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    
    @Column(name="CAMERA_CRATE", length=10)
    public String getCameraCrate() {
        return this.cameraCrate;
    }
    
    public void setCameraCrate(String cameraCrate) {
        this.cameraCrate = cameraCrate;
    }

    
    @Column(name="CAMERA_DRIVER", precision=10, scale=0)
    public Long getCameraDriver() {
        return this.cameraDriver;
    }
    
    public void setCameraDriver(Long cameraDriver) {
        this.cameraDriver = cameraDriver;
    }

    
    @Column(name="CAMERA_MUX", precision=10, scale=0)
    public Long getCameraMux() {
        return this.cameraMux;
    }
    
    public void setCameraMux(Long cameraMux) {
        this.cameraMux = cameraMux;
    }

	/**
	 * toString().
	 */
	@Override
	public String toString() {
		MyPrinterHandler<TImages> handler = new MyPrinterHandler<TImages>(this, " ");
		try {
			handler.add(this.getClass().getDeclaredMethod("getImageId", (Class[]) null));
			handler.add(this.getClass().getDeclaredMethod("getImageName", (Class[]) null));
			
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return handler.print();
	}



}


